In [13]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [11]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        print(os.path.join(root, file))

/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv


In [14]:
df = pd.read_csv("/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv")
df.head()
                 

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [15]:
df.shape

(569, 32)

In [16]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [17]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')


In [ ]:
print(df.head())

In [18]:
X = df.drop(columns=["id", "diagnosis"])
y = df["diagnosis"]

In [19]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [22]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [23]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [24]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**y_train data ko label se number me convert dega ye pahle fit_transform se data learn krega then convert krega4**
****

In [ ]:
y_train

In [25]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

**torch.from_numpy se hm numpy array ko tensor me convert kr skte**

In [ ]:
x_train_tensor.shape

In [ ]:
x_test_tensor.shape


In [ ]:
y_train_tensor.shape

In [ ]:
y_test_tensor.shape

In [26]:
x_train_tensor.shape

torch.Size([455, 30])

In [27]:
import torch
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

   

**torch.optim=provide variety of optimizer it handles weight updates so efficiently
**

In [3]:
learning_rate = 0.1
epochs = 15

In [36]:
loss_function = nn.BCELoss()

In [37]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [28]:
X = df.drop(columns=["id", "diagnosis"])
y = df["diagnosis"]

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

learning rate = modelko btata training time parameters/weight ko kitna change krna hai 
epochs = Model poore dataset ko kitni baar dekhega


In [29]:
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.float32).reshape(-1, 1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).reshape(-1, 1)

In [42]:
model = MySimpleNN(x_train_tensor.shape[1])
#creating optimizer with the help of optim
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

    # forward pass
    y_pred = model(x_train_tensor)

    # loss_function calll
    loss = loss_function(y_pred,y_train_tensor)

    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

    # backward pass
    loss.backward()

    # updating parameters
    optimizer.step()
    # zero gradients
    optimizer.zero_grad

Epoch: 1, Loss: 0.6292330026626587
Epoch: 2, Loss: 0.48252958059310913
Epoch: 3, Loss: 0.32581627368927
Epoch: 4, Loss: 0.22923797369003296
Epoch: 5, Loss: 0.17924168705940247
Epoch: 6, Loss: 0.1540994942188263
Epoch: 7, Loss: 0.1406479924917221
Epoch: 8, Loss: 0.13231779634952545
Epoch: 9, Loss: 0.12602007389068604
Epoch: 10, Loss: 0.12038392573595047
Epoch: 11, Loss: 0.1149466410279274
Epoch: 12, Loss: 0.10982533544301987
Epoch: 13, Loss: 0.10550245642662048
Epoch: 14, Loss: 0.10236235707998276
Epoch: 15, Loss: 0.10027806460857391


model.paraemetr is an iterator

In [32]:
model.linear.weight

Parameter containing:
tensor([[ 0.1212,  0.1637,  0.2069,  0.2252, -0.0326,  0.0507,  0.0569,  0.3695,
          0.0564, -0.1251,  0.1599, -0.0027,  0.0720,  0.1961, -0.0368,  0.1503,
         -0.1109, -0.0763,  0.0864,  0.0933,  0.1347,  0.0209,  0.2141,  0.2276,
          0.2443,  0.0961,  0.0925,  0.4069,  0.0268,  0.1134]],
       requires_grad=True)

In [33]:
model.linear.bias

Parameter containing:
tensor([-0.0329], requires_grad=True)

In [43]:
#model evaluation
with torch.no_grad():#graditent tracking bcm of with this line
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy:{accuracy.item()}')
print(y_pred)
    

Accuracy:0.9649122953414917
tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
      

model train krne ke liye 3 steps
1.forward pass
2.loss calculate
3.backward pass
4.update parameters

ye sara loop me krte jitna epochs define hota

