In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        print(os.path.join(root, file))

/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv


In [3]:
df = pd.read_csv("/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv")
df.head()
                 

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [4]:
df.shape

(569, 32)

In [5]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [6]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')


In [7]:
print(df.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_wor

In [8]:
X = df.drop(columns=["id", "diagnosis"])
y = df["diagnosis"]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [12]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**y_train data ko label se number me convert dega ye pahle fit_transform se data learn krega then convert krega4**
****

In [14]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [15]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

**torch.from_numpy se hm numpy array ko tensor me convert kr skte**

In [16]:
x_train_tensor.shape

torch.Size([455, 30])

In [17]:
x_test_tensor.shape


torch.Size([114, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

In [19]:
y_test_tensor.shape

torch.Size([114])

In [20]:
x_train_tensor.shape

torch.Size([455, 30])

In [21]:
class MySimpleNN():
    def __init__(self, x):
        self.weight = torch.rand(
            x.shape[1], 1,
            dtype=torch.float64,
            requires_grad=True
        )
        self.bias = torch.zeros(
            1,
            dtype=torch.float64,
            requires_grad=True
        )

    def forward(self, x):
        z = torch.matmul(x, self.weight) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
        return loss.mean()

In [22]:
learning_rate = 0.1
epochs = 15

learning rate = modelko btata training time parameters/weight ko kitna change krna hai 
epochs = Model poore dataset ko kitni baar dekhega


In [23]:
model = MySimpleNN(x_train_tensor)

for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(x_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

    # backward pass
    loss.backward()

    # updating parameters
    with torch.no_grad():
        model.weight -= learning_rate * model.weight.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weight.grad.zero_()
    model.bias.grad.zero_()
    #prnt loss in each epochs
    print(f'Epochs:{epochs+1},loss:{loss.item()}')

Epoch: 0, Loss: 3.350595410149852
Epochs:16,loss:3.350595410149852
Epoch: 1, Loss: 3.216512764480958
Epochs:16,loss:3.216512764480958
Epoch: 2, Loss: 3.0754631309433433
Epochs:16,loss:3.0754631309433433
Epoch: 3, Loss: 2.925909952143634
Epochs:16,loss:2.925909952143634
Epoch: 4, Loss: 2.771662162859357
Epochs:16,loss:2.771662162859357
Epoch: 5, Loss: 2.6126678441971927
Epochs:16,loss:2.6126678441971927
Epoch: 6, Loss: 2.449440311452337
Epochs:16,loss:2.449440311452337
Epoch: 7, Loss: 2.283266739722213
Epochs:16,loss:2.283266739722213
Epoch: 8, Loss: 2.118526157783404
Epochs:16,loss:2.118526157783404
Epoch: 9, Loss: 1.9504285601197544
Epochs:16,loss:1.9504285601197544
Epoch: 10, Loss: 1.786174948176514
Epochs:16,loss:1.786174948176514
Epoch: 11, Loss: 1.6308115735165243
Epochs:16,loss:1.6308115735165243
Epoch: 12, Loss: 1.4822425248546747
Epochs:16,loss:1.4822425248546747
Epoch: 13, Loss: 1.343572074128567
Epochs:16,loss:1.343572074128567
Epoch: 14, Loss: 1.2205553806727085
Epochs:16,lo

In [24]:
model.weight

tensor([[ 0.3358],
        [-0.1474],
        [ 0.0198],
        [-0.0350],
        [ 0.1231],
        [ 0.2829],
        [-0.1435],
        [ 0.0191],
        [ 0.4143],
        [ 0.4775],
        [-0.1194],
        [ 0.4765],
        [-0.0616],
        [-0.1525],
        [ 0.6888],
        [ 0.3580],
        [ 0.4050],
        [ 0.5193],
        [-0.1188],
        [-0.0602],
        [ 0.2198],
        [ 0.3194],
        [ 0.2433],
        [ 0.3857],
        [-0.2106],
        [-0.1322],
        [-0.1758],
        [-0.2807],
        [ 0.3733],
        [ 0.0236]], dtype=torch.float64, requires_grad=True)

In [25]:
model.bias

tensor([-0.0761], dtype=torch.float64, requires_grad=True)

In [26]:
#model evaluation
with torch.no_grad():#graditent tracking bcm of with this line
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 18.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy:{accuracy.item()}')
print(y_pred)
    

Accuracy:0.6228070259094238
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

model train krne ke liye 3 steps
1.forward pass
2.loss calculate
3.backward pass
4.update parameters

ye sara loop me krte jitna epochs define hota

