In [1]:
import torch
x = torch.tensor([3,6,8])
print(x)
print( 20 + 2)

tensor([3, 6, 8])
22


In [2]:
import torch
import torch.nn as nn
model = nn.Linear(2,1)
x = torch.tensor([[2.0,3.0]])
output = model(x)
print(output)

tensor([[-0.3836]], grad_fn=<AddmmBackward0>)


In [3]:
import torch
import torch.nn as nn
model = nn.Linear(1,1)
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
x = torch.tensor([[1.0],[2.0],[3.0]])
y = torch.tensor([[2.0],[4.0],[6.0]])
for epoch in range(100):
    prediction = model(x)
    loss = loss_fn(prediction,y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

print(model(torch.tensor([[4.0]])))

tensor([[7.3044]], grad_fn=<AddmmBackward0>)


In [4]:
# tensor computation--to perform mathematical operations on tensor
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,1])
print(a+b)

tensor([5, 7, 4])


In [5]:
import torch
a = torch.tensor([2,3,4])
b = torch.tensor([1,2,3])
print (a-b)

tensor([1, 1, 1])


In [6]:
import torch
a = torch.tensor([1,1,1])
b = torch.tensor([0,0,0])
print(a*b)

tensor([0, 0, 0])


In [7]:
import torch
a = torch.tensor([4,8,16])
b = torch.tensor([2,4,8])
print(a/b)

tensor([2., 2., 2.])


In [8]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])
c = torch.matmul(A, B)
print(c)

d = torch.add(A,B)
print(d)

tensor([[19, 22],
        [43, 50]])
tensor([[ 6,  8],
        [10, 12]])


In [9]:
#how to check gpu in pytorch
import torch
print(torch.cuda.is_available())

False


In [10]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.tensor([1, 2, 3])

x = x.to(device)

print(x)
print(x.device)

tensor([1, 2, 3])
cpu


In [11]:
import torch
x = torch.tensor(4.0,requires_grad=True)
y = x**2
y.backward()
print(x.grad)

tensor(8.)
